# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

[fill]
symbol = ' '
# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[󰄛](mauve) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "mauve"
symbol = " "

[directory]
truncation_length = 4
style = "bold lavender"
read_only = " 󰌾"
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[cmd_duration]
style = 'bold pink'

[bun]
format = "via [$symbol]($style)"

[buf]
format = "via [$symbol]($style)"
symbol = " "

[cmake]
format = "via [$symbol]($style)"

[cobol]
format = "via [$symbol]($style)"

[crystal]
format = "via [$symbol]($style)"
symbol = " "

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"
symbol = " "

[deno]
format = "via [$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = 'via [$symbol]($style)'
symbol = " "

[elm]
format = 'via [$symbol]($style)'
symbol = " "

[erlang]
format = 'via [$symbol]($style)'

[fennel]
format = 'via [$symbol]($style)'
symbol = " "

[gleam]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'
symbol = " "

[gradle]
format = 'via [$symbol]($style)'

[haxe]
format = 'via [$symbol]($style)'
symbol = " "

[helm]
format = 'via [$symbol]($style)'

[java]
format = 'via [$symbol]($style)'
symbol = " "

[julia]
format = 'via [$symbol]($style)'
symbol = " "

[kotlin]
format = 'via [$symbol]($style)'
symbol = " "

[lua]
format = 'via [$symbol]($style)'
symbol = " "

[meson]
format = 'via [$symbol]($style)'
symbol = "󰔷 "

[nim]
format = 'via [$symbol]($style)'
symbol = "󰆥 "

[nodejs]
style = 'green'
format = 'via [$symbol]($style)'
symbol = " "

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'
symbol = " "

[opa]
format = 'via [$symbol]($style)'

[perl]
format = 'via [$symbol]($style)'
symbol = " "

[php]
format = 'via [$symbol]($style)'
symbol = " "

[pulumi]
format = 'via [$symbol$stack]($style)'

[purescript]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'
symbol = " "

[quarto]
format = 'via [$symbol]($style)'

[raku]
format = 'via [$symbol]($style)'

[red]
format = 'via [$symbol]($style)'

[rlang]
format = 'via [$symbol]($style)'
symbol = "󰟔 "

[ruby]
format = 'via [$symbol]($style)'
symbol = " "

[rust]
format = 'via [$symbol]($style)'
symbol = "󱘗 "

[solidity]
format = 'via [$symbol]($style)'

[typst]
format = 'via [$symbol]($style)'

[swift]
format = 'via [$symbol]($style)'
symbol = " "

[vagrant]
format = 'via [$symbol]($style)'

[vlang]
format = 'via [$symbol]($style)'

[zig]
format = 'via [$symbol]($style)'
symbol = " "

[aws]
symbol = "  "
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[c]
symbol = " "

[conda]
symbol = " "

[docker_context]
symbol = " "
style = 'fg:#74c7ec'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[fossil_branch]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
style = "green"

[pijul_channel]
symbol = " "

[scala]
symbol = " "
